const suffixes: string[] = [
  "yňyzda",
  "yňyz",
  "yň",
  "da",
  "de",
  "lary",
  "leri",
  "ýar",
  "ýan",
  "lar",
  "ler",
  "dan",
  "den",
  "-a",
  "-e",
  "nyň",
  "niň",
  "dy",
  "di",
  "dyr",
  "dir",
  "mak",
  "mek",
  "syz",
  "siz",
  "lyk",
  "lik",
  "ja",
  "je",
];

const synonyms: string[][] = [
  ["satyn almak", "almak", "satyn al"],
  ["kredit kart", "bank kart", "plastik kart"],
  ["kitap", "kitaplar", "depter"],
  ["ýol", "ýollar", "ýollar"],
  ["öý", "jaý", "ev"],
  ["adam", "kişi", "erkek"],
  ["gyz", "gyzlar", "gadin"],
  ["suw", "çäý", "syýy"],
  ["gül", "çyçek", "çyçekler"],
  ["at", "ýem", "ot"],
  ["ýaş", "ulug", "uly"],
  ["kiçi", "kiçijik", "ufak"],
  ["gara", "ýaman", "erbet"],
  ["gowy", "ýakşy", "hoş"],
  ["ýolbaşçy", "başlyk", "lider"],
  ["dost", "ýoldaş", "arkadaş"],
  ["iş", "ýumuş", "gul"],
  ["sagat", "wagt", "uakyt"],
  ["ýürek", "gönül", "kalb"],
  ["göz", "gözler", "ňäzir"],
  ["el", "eller", "gol"],
  ["baş", "başlar", "kelle"],
  ["ýer", "ýurt", "toprak"],
  ["söz", "läp", "habar"],
  ["ýagşy", "ýaramaz", "ýarawsyz"],
  ["aý", "ýyldyz", "gün"],
  ["suwuk", "ýumşak", "lyp"],
  ["maşyn", "awto", "awtomobil"],
  ["ýolbars", "pars", "gaplaň"],
  ["akyl", "zihin", "aň"],
  ["howa", "hewa", "gök"],
  ["suwag", "çöl", "ýerasty"],
  ["bilim", "ilim", "okuw"],
];

const names: string[] = [
  "Merdan",
  "Meret",
  "Annaguly",
  "Nury",
  "Gurban",
  "Sapargeldi",
  "Atageldi",
  "Allaberdi",
  "Geldi",
  "Batyr",
  "Bayram",
  "Dovlet",
  "Durdy",
  "Juma",
  "Rahman",
  "Jumamyrat",
  "Sapar",
  "Babamyrat",
  "Begench",
  "Geldimyrat",
  "Serdar",
  "Myrat",
  "Yhlas",
  "Rejep",
  "Toyly",
  "Soltan",
  "Shamyrat",
];

export const greetings: string[] = [
  "Salam!",
  "Hoş geldiňiz!",
  "Assalamu Aleýkum!",
  "Salam jan dogan!",
  "Günüň haýyrly bolsun!",
  "Eýläp geldiňmi?",
  "Salam hormatly myhman!",
  "Salam, nädip ýagdaýlaryň?",
  "Salam, bagtly gün!",
  "Salam, sag amanmy?",
];

export const farewells: string[] = [
  "Hoş sag bol!",
  "Görüşýänçä!",
  "Sag aman bol!",
  "Gürrüňdeş bolduk!",
  "Hoş gal!",
  "Özüne gowy seret!",
  "Ýene görüşeris!",
  "Öňüň açyk bolsun!",
  "Salamat boluň!",
  "Geljekde duşuşarys!",
];

const conjunctions: { tm: string; translit: string }[] = [
  { tm: "we", translit: "we" },
  { tm: "ýa", translit: "ya" },
  { tm: "ya", translit: "ya" },
  { tm: "emma", translit: "emma" },
  { tm: "şol sebäpden", translit: "shol sebapden" },
  { tm: "şuňa garamazdan", translit: "shuna garamazdan" },
  { tm: "ýogsam", translit: "yogsam" },
  { tm: "eýer", translit: "eyer" },
  { tm: "çünki", translit: "chunki" },
  { tm: "üçin", translit: "uchin" },
  { tm: "hökman", translit: "hokman" },
  { tm: "şonda", translit: "shonda" },
  { tm: "haçan", translit: "hachan" },
  { tm: "nirede", translit: "nirede" },
  { tm: "näme üçin", translit: "name ucin" },
  { tm: "näçe", translit: "nache" },
  { tm: "eýsem", translit: "eysem" },
  { tm: "ýa… ýa", translit: "ya… ya" },
  { tm: "ne… ne", translit: "ne… ne" },
  { tm: "hem… hem", translit: "hem… hem" },
  { tm: "muny bilen birlikde", translit: "muny bilen birlikde" },
  { tm: "ýöne", translit: "yone" },
  { tm: "eyyam", translit: "eyyam" },
  { tm: "eýýäm", translit: "eyyam" },
];

export { suffixes, synonyms, names, conjunctions };
